version: '3.8'

services:
  drupal:
    image: drupal:latest
    container_name: drupal
    ports:
      - "8080:80"
    volumes:
      - drupal-modules:/var/lib/postgresql/modules
      - drupal-profiles:/var/lib/postgresql/profiles
      - drupal-sites:/var/lib/postgresql/sites
      - drupal-themes:/var/lib/postgresql/themes
    environment:
      DRUPAL_DB_HOST: postgres
      DRUPAL_DB_PORT: 5432
      DRUPAL_DB_USER: drupal
      DRUPAL_DB_PASSWORD: drupal
      DRUPAL_DB_NAME: drupal
    depends_on:
      - postgres
    networks:
      - myapp1

  postgres:
    image: postgres:latest
    container_name: postgres
    environment:
      POSTGRES_USER: drupal
      POSTGRES_PASSWORD: drupal
      POSTGRES_DB: drupal
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - myapp1

networks:
  myapp1:
    external: true

volumes:
  drupal-modules:
    external: true
  drupal-profiles:
    external: true
  drupal-sites:
    external: true
  drupal-themes:
    external: true
  postgres-data:
    external: true
